#include <iostream.h>
#include <conio.h>

void main ()
{
     clrscr ();
     cout << "AAAAAAAAAA   LL          DDDDDDDDD   II\n";
     cout << "AA      AA   LL          DD     DD   II\n";
     cout << "AA      AA   LL          DD     DD   II\n";
     cout << "AAAAAAAAAA   LL          DD     DD   II\n";
     cout << "AA      AA   LL          DD     DD   II\n";
     cout << "AA      AA   LL          DD     DD   II\n";
     cout << "AA      AA   LLLLLLLLLL  DDDDDDDDD   II\n";

     getch ();
     }
